from bank_system.decorators.credit_analyst_decorator import CreditAnalystDecorator
from bank_system.decorators.bank_account_decorator import BankAccountDecorator
from bank_system.decorators.attendant_decorator import AttendantDecorator
from bank_system.decorators.employee_decorator import EmployeeDecorator
from bank_system.decorators.client_decorator import ClientDecorator
